---
title: "task2"
author: "Huiying"
date: "2022-11-27"
output: html_document
---

```{r}
library(ggplot2)
library(tidyverse)
library(GGally)
library(MASS)
library(e1071)
library(class)
library(caret)
```


```{r}
## systematic, logistic, accuracy
data=image.syst.train%>%filter(label!=0)
data$label[data$label==-1]=0
datatrain=data%>%filter(fold!=1)
dataval=data%>%filter(fold==1)
glm.fit=glm(label~NDAI+SD+CORR+DF+CF+BF+AF+AN,data=datatrain,family=binomial)
glm.probs=predict(glm.fit,dataval,type="response")
glm.pred=rep(0,length(glm.probs))
glm.pred[glm.probs>0.5]=1
mean(glm.pred==dataval$label)
```

```{r}
## K folds
K=10
cvresult=matrix(NA,ncol=2,nrow=K)
colnames(cvresult)=c("fold","acc")
fold.syst=unique(image.syst.train$fold)
set.seed(111)
fold.sample=sample(fold.syst)
for(i in 1:K){
  datatrain=data%>%filter(fold!=fold.sample[i%%K+1])
  dataval=data%>%filter(fold==fold.sample[i%%K+1])
  glm.fit=glm(label~NDAI+SD+CORR+DF+CF+BF+AF+AN,data=datatrain,family=binomial)
  glm.probs=predict(glm.fit,dataval,type="response")
  glm.pred=rep(0,length(glm.probs))
  glm.pred[glm.probs>0.5]=1
  acc=mean(glm.pred==dataval$label)
  cvresult[i,1]=i
  cvresult[i,2]=acc
}
cvresult
mean(cvresult[,2])
```

```{r}
## buff, logistic, accuracy
data=image.buf.train%>%filter(label!=0)
data$label[data$label==-1]=0
## K folds
K=10
cvresult=matrix(NA,ncol=2,nrow=K)
colnames(cvresult)=c("fold","acc")
fold.buf=unique(image.buf.train$fold)
set.seed(111)
fold.sample=sample(fold.buf)
for(i in 1:K){
  datatrain=data%>%filter(fold!=fold.sample[i%%K+1])
  dataval=data%>%filter(fold==fold.sample[i%%K+1])
  glm.fit=glm(label~NDAI+SD+CORR+DF+CF+BF+AF+AN,data=datatrain,family=binomial)
  glm.probs=predict(glm.fit,dataval,type="response")
  glm.pred=rep(0,length(glm.probs))
  glm.pred[glm.probs>0.5]=1
  acc=mean(glm.pred==dataval$label)
  cvresult[i,1]=i
  cvresult[i,2]=acc
}
cvresult
mean(cvresult[,2])
```

```{r}
## buff, lda, accuracy
data=image.buf.train%>%filter(label!=0)
data$label[data$label==-1]=0
## K folds
K=10
cvresult=matrix(NA,ncol=2,nrow=K)
colnames(cvresult)=c("fold","acc")
fold.buf=unique(image.buf.train$fold)
set.seed(111)
fold.sample=sample(fold.buf)
for(i in 1:K){
  datatrain=data%>%filter(fold!=fold.sample[i%%K+1])
  dataval=data%>%filter(fold==fold.sample[i%%K+1])
  lda.fit=lda(label~NDAI+SD+CORR+DF+CF+BF+AF+AN,data=datatrain)
  lda.pred=predict(lda.fit,dataval)
  acc=mean(lda.pred$class==dataval$label)
  cvresult[i,1]=i
  cvresult[i,2]=acc
}
cvresult
mean(cvresult[,2])
```

```{r}
## buff, qda, accuracy
data=image.buf.train%>%filter(label!=0)
data$label[data$label==-1]=0
## K folds
K=10
cvresult=matrix(NA,ncol=2,nrow=K)
colnames(cvresult)=c("fold","acc")
fold.buf=unique(image.buf.train$fold)
set.seed(111)
fold.sample=sample(fold.buf)
for(i in 1:K){
  datatrain=data%>%filter(fold!=fold.sample[i%%K+1])
  dataval=data%>%filter(fold==fold.sample[i%%K+1])
  qda.fit=qda(label~NDAI+SD+CORR+DF+CF+BF+AF+AN,data=datatrain)
  qda.pred=predict(qda.fit,dataval)
  acc=mean(qda.pred$class==dataval$label)
  cvresult[i,1]=i
  cvresult[i,2]=acc
}
cvresult
mean(cvresult[,2])
```

```{r}
## buff, naive bayes, accuracy
data=image.buf.train%>%filter(label!=0)
data$label[data$label==-1]=0
## K folds
K=10
cvresult=matrix(NA,ncol=2,nrow=K)
colnames(cvresult)=c("fold","acc")
fold.buf=unique(image.buf.train$fold)
set.seed(111)
fold.sample=sample(fold.buf)
for(i in 1:K){
  datatrain=data%>%filter(fold!=fold.sample[i%%K+1])
  dataval=data%>%filter(fold==fold.sample[i%%K+1])
  nb.fit=naiveBayes(label~NDAI+SD+CORR+DF+CF+BF+AF+AN,data=datatrain)
  nb.pred=predict(nb.fit,dataval)
  acc=mean(nb.pred==dataval$label)
  cvresult[i,1]=i
  cvresult[i,2]=acc
}
cvresult
mean(cvresult[,2])
```

```{r}
## buff, knn, k=5, accuracy
data=image.buf.train%>%filter(label!=0)
data$label[data$label==-1]=0
## K folds
K=10
cvresult=matrix(NA,ncol=2,nrow=K)
colnames(cvresult)=c("fold","acc")
fold.buf=unique(image.buf.train$fold)
set.seed(111)
fold.sample=sample(fold.buf)
for(i in 1:K){
  datatrain=data%>%filter(fold!=fold.sample[i%%K+1])
  dataval=data%>%filter(fold==fold.sample[i%%K+1])
  knn.pred=knn(datatrain[,4:11],dataval[,4:11],datatrain$label,k=5)
  acc=mean(knn.pred==dataval$label)
  cvresult[i,1]=i
  cvresult[i,2]=acc
}
cvresult
mean(cvresult[,2])
```

