---
title: "task 3a report accuracy"
author: "Yanjiao"
date: "2022-11-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# get CVmaster function
source("CVmaster.R")
```

```{r}
# accuracies across folds (systematic assignment)
acc.cv.syst = rbind(
  data.frame(model = "Logistic", 
             accuracy = CVmaster(classifier = "logistic", xtrain = image.syst.train[,4:12], ytrain = image.syst.train$label,
                                 K = 10, loss = "accuracy")),
  data.frame(model = "LDA", 
             accuracy = CVmaster(classifier = "LDA", xtrain = image.syst.train[,4:12], ytrain = image.syst.train$label,
                                 K = 10, loss = "accuracy")),
  data.frame(model = "QDA", 
             accuracy = CVmaster(classifier = "QDA", xtrain = image.syst.train[,4:12], ytrain = image.syst.train$label,
                                 K = 10, loss = "accuracy")),
  data.frame(model = "Naive Bayes", 
             accuracy = CVmaster(classifier = "Naive Bayes", xtrain = image.syst.train[,4:12], ytrain = image.syst.train$label,
                                 K = 10, loss = "accuracy")),
  data.frame(model = "KNN", 
             accuracy = CVmaster(classifier = "knn", xtrain = image.syst.train[,4:12], ytrain = image.syst.train$label,
                                 K = 10, loss = "accuracy")),
  data.frame(model = "Random Forest", 
             accuracy = CVmaster(classifier = "rf", xtrain = image.syst.train[,4:12], ytrain = image.syst.train$label,
                                 K = 10, loss = "accuracy")),
  data.frame(model = "Adaboost", 
             accuracy = CVmaster(classifier = "adaboost", xtrain = image.syst.train[,4:12], ytrain = image.syst.train$label,
                                 K = 10, loss = "accuracy"))
  ) %>%
  pivot_wider(id_cols = model, names_from = accuracy.fold, values_from = accuracy.acc)

acc.cv.syst["average"]=rowMeans(acc.cv.syst[,2:ncol(acc.cv.syst)])
```

```{r}
acc.cv.buf = rbind(
  data.frame(model = "Logistic", 
             accuracy = CVmaster(classifier = "logistic", xtrain = image.buf.train[,4:12], ytrain = image.buf.train$label,
                                 K = 10, loss = "accuracy")),
  data.frame(model = "LDA", 
             accuracy = CVmaster(classifier = "LDA", xtrain = image.buf.train[,4:12], ytrain = image.buf.train$label,
                                 K = 10, loss = "accuracy")),
  data.frame(model = "QDA", 
             accuracy = CVmaster(classifier = "QDA", xtrain = image.buf.train[,4:12], ytrain = image.buf.train$label,
                                 K = 10, loss = "accuracy")),
  data.frame(model = "Naive Bayes", 
             accuracy = CVmaster(classifier = "Naive Bayes", xtrain = image.buf.train[,4:12], ytrain = image.buf.train$label,
                                 K = 10, loss = "accuracy")),
  data.frame(model = "KNN", 
             accuracy = CVmaster(classifier = "knn", xtrain = image.buf.train[,4:12], ytrain = image.buf.train$label,
                                 K = 10, loss = "accuracy")),
  data.frame(model = "Random Forest", 
             accuracy = CVmaster(classifier = "rf", xtrain = image.buf.train[,4:12], ytrain = image.buf.train$label,
                                 K = 10, loss = "accuracy")),
  data.frame(model = "Adaboost", 
             accuracy = CVmaster(classifier = "adaboost", xtrain = image.buf.train[,4:12], ytrain = image.buf.train$label,
                                 K = 10, loss = "accuracy"))
  ) %>%
  pivot_wider(id_cols = model, names_from = accuracy.fold, values_from = accuracy.acc)

acc.cv.buf["average"]=rowMeans(acc.cv.buf[,2:ncol(acc.cv.buf)])
```